### PR TITLE
Up navigation and drawer fixes

### PR DESCRIPTION
**Pull request by ghost**
Pretty please?

### CODE REVIEW

**Comment by ischeinkman** [comment]
Settings up navigation only goes to frontpage activity, even when accessed from a different activity.

**Comment by ischeinkman** [comment]
Also why is there commented out code in the SettingsActivity?

**Comment by ghost** [comment]
I forgot to remove it after experimenting with it. I will remove it on the
my next commit.

**Comment by ghost** [comment]
I am removing this PR to create a new updated one once I fixed all the bugs.

**Pull request closed without merging**
